# Generated by Django 5.1.2 on 2025-04-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_freelancerdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
