# Generated by Django 5.1.7 on 2025-04-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recruiterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('location', models.CharField(help_text='Loction or mention remote', max_length=100)),
                ('rate_type', models.DecimalField(blank=True, decimal_places=2, help_text='hourly or fixed', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='job status')),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='When the job was originally posted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated.')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.recruiterdata')),
                ('required_skills', models.ManyToManyField(blank=True, help_text='Required Skills', related_name='jobs_requiring', to='core.skill')),
            ],
            options={
                'ordering': ['posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING REVIEW'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('cover_letter', models.TextField(blank=True, help_text='optional', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.freelancerdata')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
            ],
            options={
                'ordering': ['applied_at'],
                'unique_together': {('jobs', 'freelancer')},
            },
        ),
    ]
