# Generated by Django 5.1.7 on 2025-04-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate or fixed project cost', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Job status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Location or mention remote', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='rate_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('FIXED', 'Fixed Project')], default='HOURLY', help_text='Type of compensation (e.g., Hourly, Fixed).', max_length=10),
        ),
    ]
