# Generated by Django 5.2.7 on 2025-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerdata',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='recruiterdata',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
