# Generated by Django 5.2.7 on 2025-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_freelancerdata_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerdata",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="freelancerdata",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
    ]
